http: 
  port: 8082
db:
  host:     localhost
  port: 5432
  username: postgres
  password: 123Qwer
  database: broker
bot:
  token: "123"
  webhookURL: "http://localhost"
broker:
  ID: 1
  tickers:
    - SPFB.RTS
  exchangeEndpoint: ":8081"